<a href="https://colab.research.google.com/github/enukash/Course/blob/master/EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#EXPLORATORY DATA ANALYSIS(EDA) - PRE MACHINE LEARNING
#EDA- We find different insights, we come to different conclusions , we explore our DATASET
#DATASET: https://storage.googleapis.com/kagglesdsdata/datasets/9590/13660/fruit_data_with_colors.txt?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20230802%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20230802T144611Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=12150c26bf58c3caceaa596ef2a075a20c83dba3f864f19576273be0cf86a269a42f7fddcf11300e07b9924366de61047f975fa32fd6eeaf1ad1c684cdf1ff104e31a98c9656de17f1181d5265cb2edb2a261e4e4de9e6fb919b049ca63760a8c771221c2e3ac6036544f75ee3528e30533adae33cb00c82f686895c3d8080a32f25f0808e661a73c752afcb81353e6bdd08627045e7d441d00bde43ec37e5391613e5faa37fe36a5124982e056a94b866bfd040120abdb253eec964dbe74db39f41c91fd152499857154a6d89bf0c24d5c0158afe143e92cbdc63aedd01989938bc06e148d9718dcb92704dc7d78da81001f84812e4dca0d385a34bcf5608ee

In [ ]:
#Type1- to create dataframe
# # Let us consider the data and create dataframe
# import pandas as pd
# df = pd.read_csv('https://storage.googleapis.com/kagglesdsdata/datasets/9590/13660/fruit_data_with_colors.txt?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20230802%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20230802T144611Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=12150c26bf58c3caceaa596ef2a075a20c83dba3f864f19576273be0cf86a269a42f7fddcf11300e07b9924366de61047f975fa32fd6eeaf1ad1c684cdf1ff104e31a98c9656de17f1181d5265cb2edb2a261e4e4de9e6fb919b049ca63760a8c771221c2e3ac6036544f75ee3528e30533adae33cb00c82f686895c3d8080a32f25f0808e661a73c752afcb81353e6bdd08627045e7d441d00bde43ec37e5391613e5faa37fe36a5124982e056a94b866bfd040120abdb253eec964dbe74db39f41c91fd152499857154a6d89bf0c24d5c0158afe143e92cbdc63aedd01989938bc06e148d9718dcb92704dc7d78da81001f84812e4dca0d385a34bcf5608ee',sep = '\t')
# df

In [6]:
#Type 2- to create dataframe
import pandas as pd
df = pd.read_csv('/content/fruit_data_with_colors.txt', sep = '\t')
df

    fruit_label fruit_name     fruit_subtype  mass  width  height  color_score
0             1      apple      granny_smith   192    8.4     7.3         0.55
1             1      apple      granny_smith   180    8.0     6.8         0.59
2             1      apple      granny_smith   176    7.4     7.2         0.60
3             2   mandarin          mandarin    86    6.2     4.7         0.80
4             2   mandarin          mandarin    84    6.0     4.6         0.79
5             2   mandarin          mandarin    80    5.8     4.3         0.77
6             2   mandarin          mandarin    80    5.9     4.3         0.81
7             2   mandarin          mandarin    76    5.8     4.0         0.81
8             1      apple          braeburn   178    7.1     7.8         0.92
9             1      apple          braeburn   172    7.4     7.0         0.89
10            1      apple          braeburn   166    6.9     7.3         0.93
11            1      apple          braeburn   172    7.1     7.6         0.92
12            1      apple          braeburn   154    7.0     7.1         0.88
13            1      apple  golden_delicious   164    7.3     7.7         0.70
14            1      apple  golden_delicious   152    7.6     7.3         0.69
15            1      apple  golden_delicious   156    7.7     7.1         0.69
16            1      apple  golden_delicious   156    7.6     7.5         0.67
17            1      apple  golden_delicious   168    7.5     7.6         0.73
18            1      apple       cripps_pink   162    7.5     7.1         0.83
19            1      apple       cripps_pink   162    7.4     7.2         0.85
20            1      apple       cripps_pink   160    7.5     7.5         0.86
21            1      apple       cripps_pink   156    7.4     7.4         0.84
22            1      apple       cripps_pink   140    7.3     7.1         0.87
23            1      apple       cripps_pink   170    7.6     7.9         0.88
24            3     orange     spanish_jumbo   342    9.0     9.4         0.75
25            3     orange     spanish_jumbo   356    9.2     9.2         0.75
26            3     orange     spanish_jumbo   362    9.6     9.2         0.74
27            3     orange  selected_seconds   204    7.5     9.2         0.77
28            3     orange  selected_seconds   140    6.7     7.1         0.72
29            3     orange  selected_seconds   160    7.0     7.4         0.81
30            3     orange  selected_seconds   158    7.1     7.5         0.79
31            3     orange  selected_seconds   210    7.8     8.0         0.82
32            3     orange  selected_seconds   164    7.2     7.0         0.80
33            3     orange      turkey_navel   190    7.5     8.1         0.74
34            3     orange      turkey_navel   142    7.6     7.8         0.75
35            3     orange      turkey_navel   150    7.1     7.9         0.75
36            3     orange      turkey_navel   160    7.1     7.6         0.76
37            3     orange      turkey_navel   154    7.3     7.3         0.79
38            3     orange      turkey_navel   158    7.2     7.8         0.77
39            3     orange      turkey_navel   144    6.8     7.4         0.75
40            3     orange      turkey_navel   154    7.1     7.5         0.78
41            3     orange      turkey_navel   180    7.6     8.2         0.79
42            3     orange      turkey_navel   154    7.2     7.2         0.82
43            4      lemon    spanish_belsan   194    7.2    10.3         0.70
44            4      lemon    spanish_belsan   200    7.3    10.5         0.72
45            4      lemon    spanish_belsan   186    7.2     9.2         0.72
46            4      lemon    spanish_belsan   216    7.3    10.2         0.71
47            4      lemon    spanish_belsan   196    7.3     9.7         0.72
48            4      lemon    spanish_belsan   174    7.3    10.1         0.72
49            4      lemon           unknown   132    5.8     8.7         0.73
50            4      lemon           unknown   130    6.0     8.2         0.71
51            4      lemon           unknown   116    6.0     7.5         0.72
52            4      lemon           unknown   118    5.9     8.0         0.72
53            4      lemon           unknown   120    6.0     8.4         0.74
54            4      lemon           unknown   116    6.1     8.5         0.71
55            4      lemon           unknown   116    6.3     7.7         0.72
56            4      lemon           unknown   116    5.9     8.1         0.73
57            4      lemon           unknown   152    6.5     8.5         0.72
58            4      lemon           unknown   118    6.1     8.1         0.70

In [7]:
df.info() #It gives us the complete  information about the dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   fruit_label    59 non-null     int64
 1   fruit_name     59 non-null     object
 2   fruit_subtype  59 non-null     object
 3   mass           59 non-null     int64
 4   width          59 non-null     float64
 5   height         59 non-null     float64
 6   color_score    59 non-null     float64
dtypes: float64(3), int64(2), object(2)
memory usage: 3.4+ KB

In [9]:
df.shape # 59 rows and 7 cols

(59, 7)

In [10]:
df.size # size tells us the total number of elements in the dataframe

413

In [ ]:
#SLICING PART
#SLICE ROW INDEXEX from 25 to 43
#var [inclusive index:exclusive index]
df[25:44]

In [12]:
# Slice row indexe from 25 to 43 and  column indexes 0 and 1
#var.iloc[row slicing, column slicing]
df.iloc[25:44,0:2]

    fruit_label fruit_name
25            3     orange
26            3     orange
27            3     orange
28            3     orange
29            3     orange
30            3     orange
31            3     orange
32            3     orange
33            3     orange
34            3     orange
35            3     orange
36            3     orange
37            3     orange
38            3     orange
39            3     orange
40            3     orange
41            3     orange
42            3     orange
43            4      lemon

In [15]:
df_new = df[['fruit_label', 'height']]
df_new

    fruit_label  height
0             1     7.3
1             1     6.8
2             1     7.2
3             2     4.7
4             2     4.6
5             2     4.3
6             2     4.3
7             2     4.0
8             1     7.8
9             1     7.0
10            1     7.3
11            1     7.6
12            1     7.1
13            1     7.7
14            1     7.3
15            1     7.1
16            1     7.5
17            1     7.6
18            1     7.1
19            1     7.2
20            1     7.5
21            1     7.4
22            1     7.1
23            1     7.9
24            3     9.4
25            3     9.2
26            3     9.2
27            3     9.2
28            3     7.1
29            3     7.4
30            3     7.5
31            3     8.0
32            3     7.0
33            3     8.1
34            3     7.8
35            3     7.9
36            3     7.6
37            3     7.3
38            3     7.8
39            3     7.4
40            3     7.5
41            3     8.2
42            3     7.2
43            4    10.3
44            4    10.5
45            4     9.2
46            4    10.2
47            4     9.7
48            4    10.1
49            4     8.7
50            4     8.2
51            4     7.5
52            4     8.0
53            4     8.4
54            4     8.5
55            4     7.7
56            4     8.1
57            4     8.5
58            4     8.1